name: Deploy to digitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Ahmedfolio CI ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing packages
      run: npm i
    - name: Building project
      run: npm run build
    - name: handling environment file
      run: cp .env.example .env
