name: Continuous Integration

on: [push, pull_request, merge]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test --watchAll=false